name: resume
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  pdf: ^3.10.1
  printing: ^5.10.3
  slide_to_act: ^2.0.1
  image_picker: ^0.8.7+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/gifs/
    - assets/images/user.png
    - assets/images/open-cardboard-box.png
    - assets/images/open-book.png
    - assets/images/project.png
    - assets/images/thinking.png
    - assets/images/mortarboard.png
    - assets/images/handshake.png
    - assets/images/goal.png
    - assets/images/experience.png
    - assets/images/declaration.png
    - assets/images/contact-books.png
    - assets/images/briefcase.png
    - assets/images/achievement.png